name: datalab_ml_iot
channels:
  - conda-forge
dependencies:
  - python=3.11
  - jupyterlab
  - numpy>=1.23,<2
  - matplotlib
  - pandas
  - pip>=23
  - scikit-learn
  - make
  - haversine
  - git-lfs
  - xgboost
  - paho-mqtt
  - pip:
      - tensorflow==2.16.2
      - kaggle
      - networkx
      - j2cli[yaml]
      - folium
      - nbstripout
